# Generated by Django 5.2.7 on 2025-12-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blogpost_practicearea_sitepage_casestudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Clear, practical legal advice', max_length=200)),
                ('hero_subheading', models.TextField(default='Commercial & Employment law • Ireland & UK\nFast, focused opinions and advocacy.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
