# Generated by Django 5.2.7 on 2025-12-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
