# Generated by Django 5.2.7 on 2025-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_blogpost_source_name_blogpost_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='citation_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='citation_url',
            field=models.URLField(blank=True),
        ),
    ]
