# Generated by Django 5.0.3 on 2025-12-09 19:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_casestudy_citation_name_casestudy_citation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full description with formatting for the detail page'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='short_summary',
            field=models.CharField(blank=True, help_text='Brief summary for practice area cards (1-2 lines)', max_length=255),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='description',
            field=models.TextField(blank=True, help_text="DEPRECATED: Use 'body' field instead"),
        ),
    ]
