# Generated by Django 5.0.3 on 2025-12-09 19:10

from django.db import migrations
import re


def migrate_practice_area_content(apps, schema_editor):
    """
    Copy existing description field to body field and generate short_summary
    from the first ~160 characters.
    """
    PracticeArea = apps.get_model('pages', 'PracticeArea')

    for area in PracticeArea.objects.all():
        # Copy description to body if body is empty
        if area.description and not area.body:
            area.body = area.description

        # Generate short_summary if empty
        if area.description and not area.short_summary:
            # Strip HTML tags and get first ~160 chars
            clean_text = re.sub(r'<[^>]+>', '', area.description)
            # Get first sentence or ~160 chars, whichever is shorter
            short = clean_text[:160].strip()
            # Try to end at a sentence boundary
            if len(clean_text) > 160:
                # Find last period, exclamation, or question mark before char 160
                last_punct = max(short.rfind('.'), short.rfind('!'), short.rfind('?'))
                if last_punct > 60:  # Don't make it too short
                    short = short[:last_punct + 1]
                else:
                    short = short + '...'
            area.short_summary = short

        area.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - clear body and short_summary fields
    """
    PracticeArea = apps.get_model('pages', 'PracticeArea')
    PracticeArea.objects.all().update(body='', short_summary='')


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_practicearea_body_practicearea_short_summary_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_practice_area_content, reverse_migration),
    ]
