# Generated by Django 5.0.3 on 2025-12-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_migrate_practice_area_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subheading',
            field=models.TextField(default='Focused expertise in commercial, criminal, general practice, and personal injury matters. Direct Professional Access provided.'),
        ),
    ]
