# Generated by Django 5.0.3 on 2025-12-09 19:51

from django.db import migrations


def update_homepage_subheading(apps, schema_editor):
    """Update existing HomepageSettings record with new subheading"""
    HomepageSettings = apps.get_model('pages', 'HomepageSettings')
    try:
        homepage = HomepageSettings.objects.get(pk=1)
        # Only update if it still has the old default value
        old_default = "Commercial & Employment law • Ireland & UK\nFast, focused opinions and advocacy."
        if homepage.hero_subheading == old_default:
            homepage.hero_subheading = "Focused expertise in commercial, criminal, general practice, and personal injury matters. Direct Professional Access provided."
            homepage.save()
    except HomepageSettings.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_update_homepage_hero_subheading'),
    ]

    operations = [
        migrations.RunPython(update_homepage_subheading, migrations.RunPython.noop),
    ]
