# Generated by Django 5.0.3 on 2025-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_update_existing_homepage_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of availability')),
                ('start_time', models.TimeField(help_text='Start time (e.g., 14:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 15:00)')),
                ('slot_type', models.CharField(choices=[('initial', 'Initial Consultation'), ('followup', 'Follow-up'), ('general', 'General')], default='initial', help_text='Type of consultation', max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this slot is currently bookable')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to public)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Availability Slot',
                'verbose_name_plural': 'Availability Slots',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
