# Generated by Django 5.0.3 on 2025-12-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_availabilityslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=120)),
                ('email', models.EmailField(help_text='Client email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Client phone number (optional)', max_length=50)),
                ('description', models.TextField(help_text='Brief description of the matter')),
                ('is_paid', models.BooleanField(default=False, help_text='Whether payment has been received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(help_text='The availability slot being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pages.availabilityslot')),
            ],
            options={
                'verbose_name': 'Booking Submission',
                'verbose_name_plural': 'Booking Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
