"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.
BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings - MUST be set via environment variables
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if os.getenv("DEBUG") == "True":
        # Development fallback - unsafe for production
        SECRET_KEY = "django-insecure-pg^h_n*gd#99gw1$82_^+4u=4#w2-o@#=yx_ydrq#=60h%#488"
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production")

DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",") if os.getenv("ALLOWED_HOSTS") else []

# Application-specific settings
CALENDLY_SIGNING_KEY = os.getenv("CALENDLY_SIGNING_KEY", "")
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "")
LLM_API_KEY  = os.getenv("LLM_API_KEY", "")
LLM_MODEL    = os.getenv("LLM_MODEL", "deepseek-chat")
ASSISTANT_ENABLED = os.getenv("ASSISTANT_ENABLED", "0") == "1"

# Calendar Feed (private iCal subscription)
CALENDAR_FEED_SECRET = os.getenv("CALENDAR_FEED_SECRET", "")

# Barrister/Site Configuration
# These are used in templates and calendar feed
SITE_NAME = os.getenv("SITE_NAME", "David Nugent BL")
BARRISTER_NAME = os.getenv("BARRISTER_NAME", "David Nugent")
BARRISTER_EMAIL = os.getenv("BARRISTER_EMAIL", "david.nugent@lawlibrary.ie")
BARRISTER_PHONE = os.getenv("BARRISTER_PHONE", "01 291 6043")
BARRISTER_MOBILE = os.getenv("BARRISTER_MOBILE", "")
CHAMBERS_ADDRESS_LINE1 = os.getenv("CHAMBERS_ADDRESS_LINE1", "Law Library, Four Courts")
CHAMBERS_ADDRESS_LINE2 = os.getenv("CHAMBERS_ADDRESS_LINE2", "Dublin 7, Ireland")
CHAMBERS_DX = os.getenv("CHAMBERS_DX", "301175")
YEAR_CALLED = os.getenv("YEAR_CALLED", "2021")
PRACTICE_AREAS_SHORT = os.getenv("PRACTICE_AREAS_SHORT", "Commercial/Chancery, Criminal, General Practice, Tort & Personal Injury")
BARRISTER_BIO_FOOTER = os.getenv("BARRISTER_BIO_FOOTER", "Junior Counsel practising in Commercial/Chancery, Criminal, General Practice, and Tort & Personal Injury Law. Dublin, Eastern & Midland Circuits.")
CIRCUITS = os.getenv("CIRCUITS", "Dublin, Eastern & Midland")
QUALIFICATIONS = os.getenv("QUALIFICATIONS", "LLB (Hons) Irish Law, BL")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "barrister-site-cache"
    }
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pages",
    "ckeditor",
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "Templates"],  # <- your capitalised folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pages.context_processors.assistant_enabled",
                "pages.context_processors.barrister_config",
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/site-access-dk2847/'
LOGIN_REDIRECT_URL = '/owner/'
LOGOUT_REDIRECT_URL = '/'

# Media files (uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Production security settings
# These should be enabled when deploying to production (DEBUG=False)
if not DEBUG:
    # HTTPS/SSL settings
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
